import { bikePack } from "./bike/pack";

export type { ActionKey } from "./bike/actions";
export { FRAME_ASSET_REV } from "./bike/frames/frameAssetUrl";
export { frameTierResolveDebug } from "./bike/frames/tierCatalog";
export { resolveStemUrl as resolvePackStemUrl } from "./bike/actions";
export {
  runBlockCursorChase,
  endBlockCursorChase,
} from "./bike/blockCursorChase";

/**
 * The single character pack baked into this build.
 * Generated by tools/template/init-new-pack.ps1
 */
export const activeCharacter = bikePack;
