# Initialize a new character pack in this repo (1 repo = 1 character = 1 .exe).
#
# Usage:
#   .\tools\template\init-new-pack.ps1 -CharacterId fox -DisplayName Fox -AppName FoxCompanion
#
param(
    [Parameter(Mandatory = $true)]
    [string]$CharacterId,

    [Parameter(Mandatory = $true)]
    [string]$DisplayName,

    [Parameter(Mandatory = $true)]
    [string]$AppName,

    [string]$Author = "ToriiLabs",
    [string]$Description = "A small desktop companion",
    [int]$BlockBridgePort = 7727
)

$ErrorActionPreference = "Stop"
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$TemplateDir = Join-Path $RepoRoot "tools\template\character-pack"
$PackDir = Join-Path $RepoRoot "src\companion\characters\$CharacterId"
$ActiveTs = Join-Path $RepoRoot "src\companion\characters\active.ts"
$BrandingJson = Join-Path $RepoRoot "branding.json"
$BrandingTemplate = Join-Path $RepoRoot "tools\template\branding.template.json"
$PackageJson = Join-Path $RepoRoot "package.json"

if (Test-Path $PackDir) {
    throw "Pack directory already exists: $PackDir"
}

Write-Host "[init-new-pack] copying template -> $PackDir"
New-Item -ItemType Directory -Path $PackDir -Force | Out-Null
Copy-Item -Recurse (Join-Path $TemplateDir "frames") (Join-Path $PackDir "frames")

$replacements = @{
    "{{CHARACTER_ID}}" = $CharacterId
    "{{DISPLAY_NAME}}" = $DisplayName
    "{{APP_NAME}}"     = $AppName
    "{{AUTHOR}}"       = $Author
    "{{DESCRIPTION}}"  = $Description
    "{{YEAR}}"         = (Get-Date).Year.ToString()
}

function Expand-TemplateFile {
    param([string]$Src, [string]$Dst)
    $text = Get-Content $Src -Raw -Encoding UTF8
    foreach ($key in $replacements.Keys) {
        $text = $text.Replace($key, $replacements[$key])
    }
    Set-Content -Path $Dst -Value $text -Encoding UTF8 -NoNewline
}

Expand-TemplateFile (Join-Path $TemplateDir "pack.ts") (Join-Path $PackDir "pack.ts")
Expand-TemplateFile (Join-Path $TemplateDir "actions.ts") (Join-Path $PackDir "actions.ts")
Expand-TemplateFile (Join-Path $TemplateDir "useLayers.ts") (Join-Path $PackDir "useLayers.ts")

# Rename export in pack.ts: characterPack -> ${CharacterId}Pack
$packTs = Get-Content (Join-Path $PackDir "pack.ts") -Raw -Encoding UTF8
$exportName = "${CharacterId}Pack"
$packTs = $packTs -replace "export const characterPack", "export const $exportName"
Set-Content (Join-Path $PackDir "pack.ts") -Value $packTs -Encoding UTF8 -NoNewline

# active.ts
$activeContent = @"
import { $exportName } from "./$CharacterId/pack";

export type { ActionKey } from "./$CharacterId/actions";

/**
 * The single character pack baked into this build.
 * Generated by tools/template/init-new-pack.ps1
 */
export const activeCharacter = $exportName;
"@
Set-Content -Path $ActiveTs -Value $activeContent -Encoding UTF8

# branding.json
Expand-TemplateFile $BrandingTemplate $BrandingJson
$branding = Get-Content $BrandingJson -Raw -Encoding UTF8 | ConvertFrom-Json
$branding.blockBridgePort = $BlockBridgePort
$branding | ConvertTo-Json -Depth 4 | Set-Content $BrandingJson -Encoding UTF8

# package.json name
$pkg = Get-Content $PackageJson -Raw -Encoding UTF8 | ConvertFrom-Json
$pkg.name = $CharacterId
$pkg.description = $Description
$pkg | ConvertTo-Json -Depth 6 | Set-Content $PackageJson -Encoding UTF8

# placeholder idle.png
Write-Host "[init-new-pack] generating placeholder idle.png"
Push-Location $RepoRoot
py -3 tools/template/character-pack/generate-placeholder-idle.py
Pop-Location

# icons
Write-Host "[init-new-pack] building tray + app icons"
Push-Location $RepoRoot
py -3 scripts/pack-tools/build-tray-icon.py
py -3 scripts/pack-tools/build-app-icon.py
Pop-Location

Write-Host ""
Write-Host "Done. Next steps:"
Write-Host "  1. npm run dev"
Write-Host "  2. Replace src/companion/assets/frames/idle.png with your character art"
Write-Host "  3. Add actions in src/companion/characters/$CharacterId/actions.ts"
Write-Host "  4. npm run build:icons && npm run dist"
