#!/usr/bin/env bash
# Initialize a new character pack in this repo.
#
# Usage:
#   ./tools/template/init-new-pack.sh fox Fox FoxCompanion
#
set -euo pipefail

CHARACTER_ID="${1:?CharacterId required}"
DISPLAY_NAME="${2:?DisplayName required}"
APP_NAME="${3:?AppName required}"
AUTHOR="${4:-ToriiLabs}"
DESCRIPTION="${5:-A small desktop companion}"
BLOCK_BRIDGE_PORT="${6:-7727}"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TEMPLATE_DIR="$REPO_ROOT/tools/template/character-pack"
PACK_DIR="$REPO_ROOT/src/companion/characters/$CHARACTER_ID"
EXPORT_NAME="${CHARACTER_ID}Pack"
YEAR="$(date +%Y)"

if [[ -d "$PACK_DIR" ]]; then
  echo "Pack directory already exists: $PACK_DIR" >&2
  exit 1
fi

echo "[init-new-pack] copying template -> $PACK_DIR"
mkdir -p "$PACK_DIR"
cp -R "$TEMPLATE_DIR/frames" "$PACK_DIR/"

substitute() {
  local src="$1" dst="$2"
  sed \
    -e "s/{{CHARACTER_ID}}/$CHARACTER_ID/g" \
    -e "s/{{DISPLAY_NAME}}/$DISPLAY_NAME/g" \
    -e "s/{{APP_NAME}}/$APP_NAME/g" \
    -e "s/{{AUTHOR}}/$AUTHOR/g" \
    -e "s/{{DESCRIPTION}}/$DESCRIPTION/g" \
    -e "s/{{YEAR}}/$YEAR/g" \
    "$src" > "$dst"
}

substitute "$TEMPLATE_DIR/pack.ts" "$PACK_DIR/pack.ts"
substitute "$TEMPLATE_DIR/actions.ts" "$PACK_DIR/actions.ts"
substitute "$TEMPLATE_DIR/useLayers.ts" "$PACK_DIR/useLayers.ts"
sed -i.bak "s/export const characterPack/export const $EXPORT_NAME/" "$PACK_DIR/pack.ts"
rm -f "$PACK_DIR/pack.ts.bak"

cat > "$REPO_ROOT/src/companion/characters/active.ts" <<EOF
import { $EXPORT_NAME } from "./$CHARACTER_ID/pack";

export type { ActionKey } from "./$CHARACTER_ID/actions";
export { FRAME_ASSET_REV } from "./$CHARACTER_ID/frames/frameAssetUrl";
export { frameTierResolveDebug } from "./$CHARACTER_ID/frames/tierCatalog";
export { resolveStemUrl as resolvePackStemUrl } from "./$CHARACTER_ID/actions";

/** Generated by tools/template/init-new-pack.sh */
export const activeCharacter = $EXPORT_NAME;
EOF

substitute "$REPO_ROOT/tools/template/branding.template.json" "$REPO_ROOT/branding.json"
node -e "
const fs=require('fs');
const p='$REPO_ROOT/branding.json';
const b=JSON.parse(fs.readFileSync(p,'utf8'));
b.blockBridgePort=$BLOCK_BRIDGE_PORT;
fs.writeFileSync(p, JSON.stringify(b,null,2)+'\n');
"

node -e "
const fs=require('fs');
const p='$REPO_ROOT/package.json';
const pkg=JSON.parse(fs.readFileSync(p,'utf8'));
pkg.name='$CHARACTER_ID';
pkg.description='$DESCRIPTION';
fs.writeFileSync(p, JSON.stringify(pkg,null,2)+'\n');
"

cd "$REPO_ROOT"
py -3 tools/template/character-pack/generate-placeholder-idle.py
py -3 scripts/pack-tools/build-tray-icon.py
py -3 scripts/pack-tools/build-app-icon.py

echo ""
echo "Done. Run: npm run dev"
