# Initialize a new character pack in this repo (1 repo = 1 character = 1 .exe).
# Bike2-derived template: block cursor chase, tire tracks, bottom-left idle + drag.
#
# Usage:
#   .\tools\template\init-new-pack.ps1 -CharacterId fox -DisplayName Fox -AppName FoxCompanion
#   .\tools\template\init-new-pack.ps1 -CharacterId fox ... -ClearPreviousPacks
#
param(
    [Parameter(Mandatory = $true)]
    [string]$CharacterId,

    [Parameter(Mandatory = $true)]
    [string]$DisplayName,

    [Parameter(Mandatory = $true)]
    [string]$AppName,

    [string]$Author = "ToriiLabs",
    [string]$Description = "A small desktop companion",
    [int]$BlockBridgePort = 7727,

    [switch]$ClearPreviousPacks
)

$ErrorActionPreference = "Stop"
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$TemplateDir = Join-Path $RepoRoot "tools\template\character-pack"
$CharactersDir = Join-Path $RepoRoot "src\companion\characters"
$PackDir = Join-Path $CharactersDir $CharacterId
$ActiveTs = Join-Path $CharactersDir "active.ts"
$BrandingJson = Join-Path $RepoRoot "branding.json"
$BrandingTemplate = Join-Path $RepoRoot "tools\template\branding.template.json"
$PackageJson = Join-Path $RepoRoot "package.json"

if (Test-Path $PackDir) {
    throw "Pack directory already exists: $PackDir (remove it or use another -CharacterId)"
}

if ($ClearPreviousPacks) {
    Write-Host "[init-new-pack] removing previous character pack directories"
    Get-ChildItem $CharactersDir -Directory | ForEach-Object {
        if ($_.Name -eq $CharacterId) { return }
        Write-Host "  - $($_.FullName)"
        Remove-Item $_.FullName -Recurse -Force
    }
}

Write-Host "[init-new-pack] copying template -> $PackDir"
New-Item -ItemType Directory -Path $PackDir -Force | Out-Null

$replacements = @{
    "{{CHARACTER_ID}}" = $CharacterId
    "{{DISPLAY_NAME}}" = $DisplayName
    "{{APP_NAME}}"     = $AppName
    "{{AUTHOR}}"       = $Author
    "{{DESCRIPTION}}"  = $Description
    "{{YEAR}}"         = (Get-Date).Year.ToString()
}

function Write-Utf8NoBom {
    param([string]$Path, [string]$Content)
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

function Expand-TemplateText {
    param([string]$Text)
    foreach ($key in $replacements.Keys) {
        $text = $Text.Replace($key, $replacements[$key])
    }
    return $text
}

function Expand-TemplateFile {
    param([string]$Src, [string]$Dst)
    $text = Get-Content $Src -Raw -Encoding UTF8
    Write-Utf8NoBom -Path $Dst -Content (Expand-TemplateText $text)
}

$skipCopy = @("generate-placeholder-idle.py")
Get-ChildItem $TemplateDir -Recurse -File | Where-Object { $skipCopy -notcontains $_.Name } | ForEach-Object {
    $rel = $_.FullName.Substring($TemplateDir.Length).TrimStart("\", "/")
    $dst = Join-Path $PackDir $rel
    $parent = Split-Path $dst -Parent
    if (-not (Test-Path $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    if ($_.Extension -eq ".ts") {
        Expand-TemplateFile $_.FullName $dst
    } else {
        Copy-Item $_.FullName $dst -Force
    }
}

$exportName = "${CharacterId}Pack"
$packTsPath = Join-Path $PackDir "pack.ts"
$packTs = Get-Content $packTsPath -Raw -Encoding UTF8
$packTs = $packTs -replace "export const characterPack", "export const $exportName"
Write-Utf8NoBom -Path $packTsPath -Content $packTs

$activeContent = @"
import { $exportName } from "./$CharacterId/pack";

export type { ActionKey } from "./$CharacterId/actions";
export { FRAME_ASSET_REV } from "./$CharacterId/frames/frameAssetUrl";
export { frameTierResolveDebug } from "./$CharacterId/frames/tierCatalog";
export { resolveStemUrl as resolvePackStemUrl } from "./$CharacterId/actions";
export {
  runBlockCursorChase,
  endBlockCursorChase,
} from "./$CharacterId/blockCursorChase";

/**
 * The single character pack baked into this build.
 * Generated by tools/template/init-new-pack.ps1
 */
export const activeCharacter = $exportName;
"@
Write-Utf8NoBom -Path $ActiveTs -Content $activeContent

Expand-TemplateFile $BrandingTemplate $BrandingJson
$branding = Get-Content $BrandingJson -Raw -Encoding UTF8 | ConvertFrom-Json
$branding.appName = $DisplayName
$branding.productName = $DisplayName
$branding.displayName = $DisplayName
$branding.characterId = $CharacterId
$branding.blockBridgePort = $BlockBridgePort
Write-Utf8NoBom -Path $BrandingJson -Content (($branding | ConvertTo-Json -Depth 4) + "`n")

$pkg = Get-Content $PackageJson -Raw -Encoding UTF8 | ConvertFrom-Json
$pkg.name = $CharacterId
$pkg.description = $Description
Write-Utf8NoBom -Path $PackageJson -Content (($pkg | ConvertTo-Json -Depth 6) + "`n")

Write-Host "[init-new-pack] generating placeholder idle.png"
Push-Location $RepoRoot
py -3 tools/template/character-pack/generate-placeholder-idle.py
Pop-Location

Write-Host "[init-new-pack] building tray + app icons"
Push-Location $RepoRoot
py -3 scripts/pack-tools/build-tray-icon.py
py -3 scripts/pack-tools/build-app-icon.py
Pop-Location

Write-Host ""
Write-Host "Done. Next steps:"
Write-Host "  1. npm run dev  (B = block chase, V/E = idle beats)"
Write-Host "  2. Import frames -> src/companion/assets/frames/  (see docs/character-pack-spec.md)"
Write-Host "  3. Copy scripts/characters/bike/ -> scripts/characters/$CharacterId/ and adapt imports"
Write-Host "  4. npm run build:icons && npm run dist"
