"""Export production part PNGs (non-overlapping) + rig-layout from char-concept-e-refined.

Run: py -3 scripts/export-ninja-parts.py
"""
from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/companion/assets/char-concept-e-refined.png"
OUT_DIR = ROOT / "src/companion/assets/parts"
LAYOUT_JSON = OUT_DIR / "rig-layout.json"
LAYOUT_TS = ROOT / "src/companion/ninja/parts/production/rigLayout.ts"

PAD = 6

# Non-overlapping pixel ownership on 681x796 (no double-draw in composite)
REGIONS: dict[str, tuple[int, int, int, int]] = {
    "shadow": (98, 712, 582, 796),
    "leftLeg": (162, 498, 318, 796),
    "rightLeg": (362, 498, 518, 796),
    "body": (198, 272, 484, 502),
    "leftArm": (22, 308, 172, 472),
    "rightArm": (508, 308, 658, 472),
    "scarf": (6, 168, 252, 292),
    "head": (96, 8, 584, 268),
}

ORIGINS: dict[str, tuple[float, float]] = {
    "shadow": (0.5, 0.5),
    "head": (0.5, 1.0),
    "body": (0.5, 0.5),
    "leftArm": (0.72, 0.22),
    "rightArm": (0.28, 0.22),
    "leftLeg": (0.52, 0.18),
    "rightLeg": (0.48, 0.18),
    "scarf": (0.82, 0.45),
}


def pad_box(
    x0: int, y0: int, x1: int, y1: int, w: int, h: int, pad: int
) -> tuple[int, int, int, int]:
    return (
        max(0, x0 - pad),
        max(0, y0 - pad),
        min(w, x1 + pad),
        min(h, y1 + pad),
    )


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"Missing {SOURCE}")

    im = Image.open(SOURCE).convert("RGBA")
    ref_w, ref_h = im.size
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    layout: dict = {
        "refWidth": ref_w,
        "refHeight": ref_h,
        "parts": {},
    }

    print(f"Source {ref_w}x{ref_h}")
    for name, (x0, y0, x1, y1) in REGIONS.items():
        bx0, by0, bx1, by1 = pad_box(x0, y0, x1, y1, ref_w, ref_h, PAD)
        crop = im.crop((bx0, by0, bx1, by1))
        out_path = OUT_DIR / f"{name}.png"
        crop.save(out_path, optimize=True)

        ox, oy = ORIGINS[name]
        layout["parts"][name] = {
            "left": bx0 / ref_w,
            "top": by0 / ref_h,
            "width": (bx1 - bx0) / ref_w,
            "height": (by1 - by0) / ref_h,
            "originX": ox,
            "originY": oy,
        }
        print(f"  {name}.png {crop.size[0]}x{crop.size[1]}")

    LAYOUT_JSON.write_text(json.dumps(layout, indent=2), encoding="utf-8")

    ts_parts = ",\n".join(
        f'  {k}: {json.dumps(v, ensure_ascii=False)}'
        for k, v in layout["parts"].items()
    )
    LAYOUT_TS.parent.mkdir(parents=True, exist_ok=True)
    LAYOUT_TS.write_text(
        f"""/** Generated by scripts/export-ninja-parts.py — do not hand-edit */
export const RIG_REF = {{ width: {ref_w}, height: {ref_h} }} as const;

export const RIG_ASPECT = RIG_REF.width / RIG_REF.height;

export type RigPartId =
  | "shadow"
  | "leftLeg"
  | "rightLeg"
  | "body"
  | "leftArm"
  | "rightArm"
  | "scarf"
  | "head";

export type RigPartLayout = {{
  left: number;
  top: number;
  width: number;
  height: number;
  originX: number;
  originY: number;
}};

export const RIG_LAYOUT: Record<RigPartId, RigPartLayout> = {{
{ts_parts}
}};
""",
        encoding="utf-8",
    )
    print(f"Wrote {LAYOUT_JSON.relative_to(ROOT)}")
    print(f"Wrote {LAYOUT_TS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
